# Generated by Django 4.2.3 on 2023-09-04 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(default='john', max_length=30)),
                ('second_name', models.CharField(default='john', max_length=30)),
                ('third_name', models.CharField(default='moses', max_length=30)),
                ('phone_number', models.CharField(default='25411223344', max_length=12)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_number', models.CharField(default='20202020', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
