# Generated by Django 4.2.3 on 2023-09-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_customuser_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='20202020', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='25411223344', max_length=12, unique=True),
        ),
    ]
