# Generated by Django 4.2.3 on 2023-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesa',
            name='PhoneNumber',
            field=models.IntegerField(default=3),
        ),
    ]
