# Generated by Django 4.2.3 on 2023-09-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mpesa_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesa',
            name='PhoneNumber',
            field=models.IntegerField(default=3, max_length=12),
        ),
    ]
