# Generated by Django 4.2.2 on 2023-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_balance_transactions_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(null=True)),
                ('PhoneNumber', models.IntegerField()),
            ],
        ),
    ]
