# Generated by Django 4.2.3 on 2023-09-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mpesa_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='receiver',
            field=models.CharField(),
        ),
    ]
