# Generated by Django 4.2.3 on 2023-09-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_paybilltranscations_tilltranscations_mpesa_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybilltranscations',
            name='transaction_id',
            field=models.CharField(default=111, max_length=30),
        ),
        migrations.AddField(
            model_name='tilltranscations',
            name='transaction_id',
            field=models.CharField(default=111, max_length=30),
        ),
    ]
