# Generated by Django 4.2.3 on 2023-09-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_transaction_id_paybilltranscations_originatorconversationid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mpesa',
            new_name='MpesaDeposits',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='TucashTransactions',
        ),
    ]
